# Generated by Django 3.2.12 on 2024-02-15 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='[["", "", ""], ["", "", ""], ["", "", ""]]', max_length=50)),
                ('player_1_icon', models.CharField(default='O', max_length=1)),
                ('player_2_icon', models.CharField(default='X', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('outcome', models.CharField(blank=True, max_length=10, null=True)),
                ('active_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_player', to=settings.AUTH_USER_MODEL)),
                ('player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
