# Generated by Django 3.2.12 on 2024-01-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='board',
            field=models.CharField(default='[["", "", ""], ["", "", ""], ["", "", ""]]', max_length=50),
        ),
    ]
